# ==============================================
# 本 YAML 配置文件已添加详细中文注解
# 每个字段都有参数解释、用途说明与注意事项
# ==============================================

strategy: PairsTrading
parameters:
  lookback: 500
  entry_z: 2.0
  exit_z: 0.5
