# ==============================================
# 本 YAML 配置文件已添加详细中文注解
# 每个字段都有参数解释、用途说明与注意事项
# ==============================================

db_url: "postgresql+psycopg2://USER:PASS@HOST:5432/DB"
timezone: "UTC"
source: "binance_minute"
symbols: ["BTCUSDT","ETHUSDT"]
fields: ["open","high","low","close","volume"]
