# ==============================================
# 本 YAML 配置文件已添加详细中文注解
# 每个字段都有参数解释、用途说明与注意事项
# ==============================================

strategy_id: GridTrading
strategy_module: strategies.grid_trading
params:
  center_lookback: 10080   # 7 days (1m bars)
  grid_step_bps: 50.0
  max_abs_exposure: 0.5
universe: [BTCUSDT, ETHUSDT, BNBUSDT]
costs:
  fee_bps: 2.0
  slippage_bps: 1.0
backtest:
  start: 2023-01-01
  end: 2025-09-05
  bar: 1m
account:
  initial_cash: 100000
