# ==============================================
# 本 YAML 配置文件已添加详细中文注解
# 每个字段都有参数解释、用途说明与注意事项
# ==============================================

strategy_id: SimpleMaker
strategy_module: strategies.simple_maker
params:
  halflife_vol: 240
  inventory_cap: 0.1
  kappa: 1.0
universe: [BTCUSDT, ETHUSDT, BNBUSDT]
costs:
  fee_bps: 1.0
  slippage_bps: 1.0
backtest:
  start: 2023-01-01
  end: 2025-09-05
  bar: 1m
account:
  initial_cash: 100000
