# ==============================================
# 本 YAML 配置文件已添加详细中文注解
# 每个字段都有参数解释、用途说明与注意事项
# ==============================================

strategy_module: strategies.momo_lowvol
objective: sharpe
params:
  - {name: momo_lb, type: int, low: 240, high: 4320}
  - {name: vol_hl, type: int, low: 30, high: 1440}
  - {name: long_n, type: int, low: 1, high: 5}
  - {name: short_n, type: int, low: 0, high: 5}
  - {name: combo_alpha, type: float, low: 0.2, high: 0.8}
trials: 150
